name: portfolio_templates
description: A new Flutter project.


publish_to: 'none' #


version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true


  assets:
    - assets/icons/
  #   - images/a_dot_ham.jpeg



  fonts:
   - family: ComforterBrush
     fonts:
        - asset: assets/fonts/ComforterBrush-Regular.ttf
#         style: italic
   - family: Satisfy
     fonts:
        - asset: assets/fonts/Satisfy-Regular.ttf
#         style: italic

   - family: SourceCodePro
     fonts:
        - asset: assets/fonts/SourceCodePro-VariableFont_wght.ttf
#         style: italic

  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
